### PR TITLE
multi environment support added for template file, now you can make t…

### PR DESCRIPTION
**Pull request by sherryt400**
In my case i need to deploy same code on two different environments i.e. staging environment and live environment so it would be great if we can make two different `.yml` file for staging and live e.g.
template-staging.yml
template-live.yml
staging one contains all the config related to staging environment and same goes for live.
I hope it explains

### CODE REVIEW

**Comment by tanhe123** [comment]
Thanks for your contribution.

**Comment by sherryt400** [comment]
can you also create tag so that i can use it from npm after update

**Comment by tanhe123** [comment]
we will release a new version this week.

**Comment by sherryt400** [comment]
thanks

**Comment by tanhe123** [comment]
new version has been released.

**Pull request merged**
